project:
  type: website
  output-dir: docs
  render:
    - about.qmd

website:
  title: "Air Quality Alerts and School Absenteeism in New York City"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Sections"
        contents:
        - about.qmd
        - 01_data.qmd

format:
  html:
    theme: 
     - cosmo
     - custom.scss
    fontsize: 1.1em
    backgroundcolor: "#EBEDFA"
    linkcolor: "#F97A1F"
    monobackgroundcolor: "#E1DFD0"



