project:
  type: website
  output-dir: docs
  render:
    - about.qmd
    - 01_data.qmd

website:
  title: "Air Quality Alerts and School Absenteeism in New York City"
  navbar:
    right:
      - text: Home
        href: about.qmd 
      - icon: github
        href: https://github.com/gsaabogado
      - icon: twitter
        href: https://twitter.com/gsaabogado
      - icon: web
        href: https://luissarmiento.net/
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Sections"
        contents:
        - about.qmd
        - 01_data.qmd
        

format:
  html:
    theme: 
     -cosmo
     -custom.scss




