project:
  type: website
  output-dir: docs
  render:
    - about.qmd
    - data.qmd

website:
  title: "Air Quality Alerts and School Absenteeism in New York City"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



