project:
  type: website
  output-dir: docs
  render:
    - about.qmd
    - 01_data.qmd

website:
  title: "Air Quality Alerts and School Absenteeism in New York City"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Sections"
        contents:
        - about.qmd
        - 01_data.qmd

format:
  html:
    theme: cosmo
    fontsize: 1.1em
    backgroundcolor: "#FEF2CD"
    css: styles.css
    toc: true



