---
title: "About"
description: |
  This website contains all the data and R-code necessary to replicate the results of the study: Air Quality Alerts and School Absences: Evidence from New York City.
author: "Luis Sarmiento"
---

# Introduction

The website contains four primary sections to accompany the study:

1. ***Data Sets*** Includes a description of all the data files. It is divided into five sub-sections

::: {.incremental}
- Data on School Absences
- Data on the forecast of the air quality index
- Data on the air quality index
- Demographic covariates
- Weather data
:::

2. ***Descriptive Statistics*** contains descriptive statistics on school absences and the forecasts of the air quality index in New York City. It is divided into two subsections; **School Absences and Demographics** and **Descriptives on the AQI Forecast**.

3. ***Methodology*** includes a rough description of the methodology I use to estimate the effect of NYC air quality health advisories on school absences. It is divided into two main sections; **Regression Discontinuity** and **Synthetic DiD**.

4. ***Results*** presents and discusses the main results of the research project. 


:::{.callout-note}
Consider that all sections contain the R-code necessary to replicate the figures, tables, and overall results of the study. Regarding the construction of the data-sets, we share the link to the dropbox repository alongside instructions to load the raw data files and transform them into the pannel data we use to estimate the effect with regression discontinuity and difference-in-difference designs.
:::

# Replication

All the raw files needed to run the code are in the [dropbox repository](https://www.dropbox.com/sh/1jyjs84sef7t1nt/AABtbantKPm4OyICNEIklpXLa?dl=0)

If you want to replicate the study:

Download all files in the [dropbox repository](https://www.dropbox.com/sh/1jyjs84sef7t1nt/AABtbantKPm4OyICNEIklpXLa?dl=0) while considering the space constraints in your computer.[^1] The files in the repository have a folder-like structure with the following key sections:

[^1]: I recommend downloading the files to an external hard drive to avoid memory issues

1.  **01_RawData** -- Includes the raw data files obtained from the New York State Department of Education, the New York State Department of Environmental Conservation, The Environmental Protection Agency, and the USA Census Buro.

2.  **02_GenData** -- Contains the data files I use for the analysis.

3.  **03_scripts** -- Here, I include all the R-scripts I use to transform the raw data into a useful format, perform descriptive statistics, and run my empirical specifications. I divide this folder into six scripts: 

::: {.incremental}
- 01_absences: Loads and clean the raw data on school absences
- 02_aqi: Loads and clean the raw data on the forecast and real measures of the air quality index
- 03_dem: Loads and clean demographic covariates obtained from the Census Buro.
- 04_weather: Loads and clean the data on weather controls
- 05_RegData: Constructs the data set for estimating the effect of air quality alerts on school absences with regression discontinuity and OLS estimators.
- 06_rd: Contains the code to estimate the effect with regression discontinuity designs
:::


4.  **AQAs_School_Absences_NYC** -- This folder contains the Quarto files necessary to replicate this website

## Raw data files

As previously mentioned, the folder 01_RawData contains all the raw files I obtained to estimate the effect of air quality health advisories on school absences.

01_schools includes all files related to school absences and school characteristics in New York City. 02_AQI has the data on the air quality index forecast from the NYSDEC and the AQI measures from the EPA. 03_weather contains several data files of weather covariates. 04_shp is a repository of shape (or spatial) files. And 05_dem includes data on neighborhood-level socio-demographic characteristics from the US Census Buro.
